CREATE TABLE items
(
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
    item_name TEXT NOT NULL,
    img_file TEXT NOT NULL, 
    item_price INTEGER NOT NULL,
    item_description TEXT NOT NULL
);

CREATE TABLE orders 
(
    order_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    comments TEXT,
    total_price INTEGER NOT NULL,
    order_summary TEXT NOT NULL
);
