CREATE TABLE items
(
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
    item_name TEXT NOT NULL,
    img_file TEXT NOT NULL, 
    item_price INTEGER NOT NULL,
    item_description TEXT NOT NULL
);